using NanoAgent.Application.Tools.Models;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace NanoAgent.Application.Tools.Serialization;

[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(ToolErrorPayload))]
[JsonSerializable(typeof(AgentDelegationResult))]
[JsonSerializable(typeof(AskQuestionResult))]
[JsonSerializable(typeof(AgentOrchestrationResult))]
[JsonSerializable(typeof(AgentOrchestrationTaskResult))]
[JsonSerializable(typeof(CodebaseIndexBuildResult))]
[JsonSerializable(typeof(CodebaseIndexCallEdge))]
[JsonSerializable(typeof(CodebaseIndexDependency))]
[JsonSerializable(typeof(CodebaseIndexListResult))]
[JsonSerializable(typeof(CodebaseIndexSearchMatch))]
[JsonSerializable(typeof(CodebaseIndexSearchResult))]
[JsonSerializable(typeof(CodebaseIndexSemanticSymbol))]
[JsonSerializable(typeof(CodebaseIndexSnippet))]
[JsonSerializable(typeof(CodebaseIndexStats))]
[JsonSerializable(typeof(CodebaseIndexStatusResult))]
[JsonSerializable(typeof(CodeIntelligenceItem))]
[JsonSerializable(typeof(CodeIntelligenceServerCandidate))]
[JsonSerializable(typeof(CodeIntelligenceServerStatus))]
[JsonSerializable(typeof(CodeIntelligenceResult))]
[JsonSerializable(typeof(HeadlessBrowserResult))]
[JsonSerializable(typeof(NanoAgent.Application.Models.LessonMemoryEntry))]
[JsonSerializable(typeof(LessonMemoryToolResult))]
[JsonSerializable(typeof(PlanUpdateItem))]
[JsonSerializable(typeof(PlanUpdateResult))]
[JsonSerializable(typeof(PlanningModeResult))]
[JsonSerializable(typeof(RepoMemoryDocumentResult))]
[JsonSerializable(typeof(RepoMemoryToolResult))]
[JsonSerializable(typeof(WorkspaceApplyPatchFileResult))]
[JsonSerializable(typeof(WorkspaceApplyPatchResult))]
[JsonSerializable(typeof(WorkspaceFileDeleteResult))]
[JsonSerializable(typeof(WorkspaceFileReadResult))]
[JsonSerializable(typeof(WorkspaceFileSearchMatch))]
[JsonSerializable(typeof(WorkspaceFileSearchResult))]
[JsonSerializable(typeof(WorkspaceFileWritePreviewLine))]
[JsonSerializable(typeof(WorkspaceFileWriteResult))]
[JsonSerializable(typeof(WorkspaceSkillLoadResult))]
[JsonSerializable(typeof(WorkspaceDirectoryListResult))]
[JsonSerializable(typeof(WorkspaceDirectoryEntry))]
[JsonSerializable(typeof(WorkspaceTextSearchResult))]
[JsonSerializable(typeof(WorkspaceTextSearchMatch))]
[JsonSerializable(typeof(WebSearchResult))]
[JsonSerializable(typeof(ShellCommandExecutionResult))]
[JsonSerializable(typeof(BackgroundTerminalInfo))]
[JsonSerializable(typeof(BackgroundTerminalListResult))]
internal sealed partial class ToolJsonContext : JsonSerializerContext
{
}
